### PR TITLE
Translate to French

### PR DESCRIPTION
**Pull request by VikoRifeo**
I can't guarantee it's perfect, but it should be more than serviceable.

### CODE REVIEW

**Comment by apace100** [comment]
Hey there! Thanks for putting so much effort into this. Unfortunately, I received another french translation yesterday already. I will push that one with the next update. If you see places where you could improve that translation, you're welcome to offer suggestions on what to change!

Thanks again, and sorry that you put so much effort into this. I'm just taking the first translation I received because I don't know French - and therefore can't judge which translation is better. I hope you understand.

**Comment by VikoRifeo** [comment]
Oof, what a coincidence. I can't seem to find this other translation? It's not in the PRs, or already merged.

**Comment by apace100** [comment]
My bad, had it commited but not pushed yet. Did that now. You can review the translation if you'd like. :) I'll leave this PR open for now in case you want to suggest any adjustments.

**Comment by VikoRifeo** [comment]
Honestly, this other translation is rather poor:

- I made an effort to be gender-neutral in my translation; the other one doesn't, preferring the masculine in all cases—except, noticeably, "Winged", which they made feminine. For reference, Minecraft itself is usually gender-neutral.
- The other translation makes some of the origins plural (Piafs, Arachnides), and others singular (Humain, Ardent); I stuck to singular to match the English version, but that doesn't matter so much as the inconsistency. In-game that would look a little funny.
- In general, the other translation is quite literal. I was a bit more poetic with mine at times. For example, my description of the Blazeborn is "A few rare people are descended from Blazes; they'll be at home near the lava-seas of the Nether." My name for "Tailwind" is "Quicksilver", and for "Aerial Combatant" I used "Extraordinary Fighter" (in the sense of a fighter jet, which is a different word in French).
- Sometimes they use "on" instead of "vous", which is an interesting choice I'm not sure how to explain. It works fine either way, but again, the inconsistency is noticeable.
- I changed the Phantom origin to "Demi-Phantom" for clarity; they translated it as "Fantôme", which means ghost (and they call Phantom form "forme fantomatique", which just sounds weird). In vanilla, Phantom is left untranslated, so I would consider this an unambiguous mistake.
- They translated "Featherweight" as "feather duster", as in the kind you use to clean your house.
- They leave "spawn" untranslated when describing Nether Inhabitant; vanilla translates it as "point de réapparition", which I also used.
- The Hot-blooded description has a typo: "Ce qui" should be "Ceci". Roughly, it's "that which" vs "this" in English.
- They translated "Orb of Origin" as "Original Orb". Unless this thing is the Platonic Form of the Sphere, I don't think that's quite right :p 
- A couple of times, they translate "Origin" as "race". I don't know if that's what you want, but again, the inconsistency is grating.
- For "View Origin", they used the verb "voir". This does mean view, but in the sense that a tourist views a landmark—it's just there and the tourist is going out of their way to see it. It would be better to use "afficher", as I did, which literally means "display" but is commonly used in computer menus where the English version would be "view".
- The "close" button became "close the window", but more importantly it uses the imperative form—the button reads like a command telling *you* to close the window.

A few other things:

- In my translations of the power descriptions, I used the future tense. They used the present, matching English. I think it flows better my way, but it's up to you.
- They translated "nocturnal" as a term for an animal with night vision. I just left it as "nocturnal". Probably doesn't matter, but it's an interesting distinction we don't really have in English.
- I don't think they got the Need for Speed reference. They just literally translated it. In mine, it's a reference to [24 Hours of Le Mans](https://en.wikipedia.org/wiki/24_Hours_of_Le_Mans), replacing 24 hours with 20 minutes, the real-world length of a Minecraft day.
- They called the Avian origin "Piafs", creating a reference to Zelda's Rito.
- I actually forgot that Ender Pearls hurt you when you use them; I thought for some reason that they hurt whatever they hit, so I translated Teleportation's description to imply you can't use them as an infinite ammo source. Oops. Just change the " (mais il n'infligera pas de dégâts)" to "– il n'infligera pas de dégâts" to fix that.
- I also de-joked the death messages a bit, into just "dried out" and "got too wet". Honestly not sure why. On the other hand, they actually added a little joke, in rhyming "mouillé" (wet) with "débrouillé" (to manage to do something).

All in all, I'd go with my translation, but their death messages (with "mouillé(e)" and "débrouillé(e)" to be gender-neutral; the other one is fine) and maybe their Avian name.

**Comment by apace100** [comment]
Those all seem like really good points. Thanks a lot for your (from my point of view) objective evaluation of the translations and their pros and cons. I contacted the author of the current translation and linked them to this conversation. They read over your translation and arguments, and seem to completely agree with what you said. They asked me to forward their thanks to you for offering your corrections on their translation, and said they learned a lot of things they will consider the next time they translate anything. :)

There are a few things I'd like to point out though:
- You named the Phantom origin "Demi-Phantom" in the translation - the original names the origin the same as the mob. Thanks for making me aware of that. Most of the origins are "half human, half something else" in nature, and I made an effort to avoid using exactly the same name as what it's referring to - Blazes are Blazeborn, Endermen are Enderians, etc. Therefore I'm actually going to rename the origin in the English localization to "Demiphantom" (probably? not sure whether "Semiphantom" would be more appropriate, or whether it needs a hyphen - I'll have to ask a native English speaker).
- I made an effort to avoid the word "race" in all places, as it might have negative connotations in some languages, regions or cultures. I'd be glad if the translations would follow that and use "origin" (or a translation thereof) in the place of the translation for "race" (like yours seems to do). Actually, I just remembered a place where I'm still using the word "race", which is a leftover from when I first began developing the mod - I'll change it for the next update.
- Using the present tense for the descriptions seemed more natural for me in this case (at least in English), as the descriptions show up in the choosing screen (where they basically mean: these are the powers you'll get), and in the viewing screen (where it shows the powers you actually have right now). Because of the second use-case for the descriptions, I think the present tense would be preferable, but if you think future tense is stylistically more appropriate in French, by all means go for it, as long as you're consistent.
- Not even I got the Need for Speed reference until you pointed it out. Honestly, I really struggled naming that power, wanting to go for something like "Freedom of Movement" at first, which then didn't seem to capture the idea of the drawback (it makes it sound more like a beneficial effect). Need for Speed crossed my mind several times, mainly because of the "requirement" aspect of needing, but I then transformed it to "Need for Mobility" in order to _avoid_ the reference (or maybe also because "heavy" armor doesn't actually slow you down, therefore making the name "Need for Speed" a bit less correct). I appreciate the effort of conserving references a lot though, even when they're unintended. ;)
- The name for the Avian origin is actually inspired by the few hours of Starbound I've played. Not sure if creating the reference to Zelda is a good idea if the English version doesn't have it.

If you want to, you're welcome to integrate the changes you suggested yourself (keeping your translation in most places, using the death messages currently in place) in this PR. It'd be extra nice if you could also add the three new command translations to your file, just so that the French translation isn't out of date as soon as I publish it with the new version. ;)

I of course would understand if you do not have the time or the desire to work more on this than you already have - your translation and analysis have been extremely helpful already - in which case you can just tell me and I'll merge the translations myself.

**Comment by VikoRifeo** [comment]
Ah, you're not a native speaker? In that case I should note, with respect to "Need for Mobility", that changing it strengthened the reference, in a way. "Mobility" is an uncommon word, so it calls attention to itself, and the practice of taking a well-known snappy line and making it deliberately clumsier is a pretty common joke in its own right.

I'm not familiar with Starbound, but a quick google tells me it hasn't been officially translated into French (or, for that matter, any languages).

**Pull request merged**
